In [ ]:
import numpy as np

from numpy import pi



1. Find a target in the dataset and delete this column from the dataset (delete by index)

In [ ]:
#dtype = [('col1', float), ('col2', float), ('col3', float), ('col4', float), ('col5', 'U20')]
#iris =np.genfromtxt('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data', delimiter=',', dtype=dtype)
iris =np.genfromtxt('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data', delimiter=',')

In [ ]:
new_iris = iris[:,~np.isnan(iris).any(axis=0)]
new_iris


array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

2. Convert the remaining columns into a 2D array (or make sure that it is already a 2D array)

In [ ]:
if isinstance(new_iris, np.ndarray):
    print("It is is a numpy array")
    if iris.ndim == 2: print('And it is 2d')
    else: print("But not 2d")
else:
    print("It is not a numpy array")

It is is a numpy array
And it is 2d


3. Calculate mean, median, standard deviation for the 1st column

In [ ]:
np.mean(new_iris,axis=0)[0]

5.843333333333334

In [ ]:
np.median(new_iris,axis=0)[0]

5.8

In [ ]:
np.std(new_iris,axis=0)[0]

0.8253012917851409

4. Insert 20 np.nan values into random positions in the array (when using normal random, positions may overlap, so find a solution that guarantees 20 unique positions)

In [ ]:
np.random.seed(20)
nan_iris = new_iris
nan_iris[np.unravel_index(np.random.choice(new_iris.size, size=20, replace=False), new_iris.shape)] = np.nan

In [ ]:
nan_iris

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, nan, nan, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, nan, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, nan, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [nan, nan, 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [nan, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

5. Find the positions of the inserted np.nan values in the 1st column


In [ ]:
nan_iris_indexes0 = np.asarray(np.isnan(nan_iris[:, 0])).nonzero()
nan_iris_indexes0

(array([ 14,  20,  43,  88, 102]),)

6. Filter the array by the condition: values in the 3rd column > 1.5 and values in the 1st column < 5.0 (save to another variable)

In [ ]:
filter_iris = new_iris[(new_iris[:,2]>1.5) & (new_iris[:,0]<5)]
filter_iris

array([[4.8, nan, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

7. Replace all np.nan values with 0

In [ ]:
new_iris[(np.isnan(new_iris))] = 0
new_iris

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 0. , 0. , 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 0. , 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 0. , 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [0. , 0. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [0. , 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

8. Count all unique values in the array and output them along with the count

In [ ]:
unique_filter_iris = np.transpose(np.unique(new_iris, return_counts=True))
unique_filter_iris

array([[ 0. , 20. ],
       [ 0.1,  6. ],
       [ 0.2, 28. ],
       [ 0.3,  7. ],
       [ 0.4,  7. ],
       [ 0.5,  1. ],
       [ 0.6,  1. ],
       [ 1. ,  8. ],
       [ 1.1,  4. ],
       [ 1.2,  7. ],
       [ 1.3, 20. ],
       [ 1.4, 20. ],
       [ 1.5, 22. ],
       [ 1.6, 11. ],
       [ 1.7,  6. ],
       [ 1.8, 12. ],
       [ 1.9,  7. ],
       [ 2. ,  7. ],
       [ 2.1,  6. ],
       [ 2.2,  6. ],
       [ 2.3, 10. ],
       [ 2.4,  6. ],
       [ 2.5, 11. ],
       [ 2.6,  5. ],
       [ 2.7,  7. ],
       [ 2.8, 14. ],
       [ 2.9, 10. ],
       [ 3. , 26. ],
       [ 3.1, 11. ],
       [ 3.2, 13. ],
       [ 3.3,  8. ],
       [ 3.4, 11. ],
       [ 3.5,  8. ],
       [ 3.6,  4. ],
       [ 3.7,  4. ],
       [ 3.8,  7. ],
       [ 3.9,  5. ],
       [ 4. ,  5. ],
       [ 4.1,  4. ],
       [ 4.2,  5. ],
       [ 4.3,  3. ],
       [ 4.4,  8. ],
       [ 4.5,  9. ],
       [ 4.6,  7. ],
       [ 4.7,  7. ],
       [ 4.8,  8. ],
       [ 4.9, 11. ],
       [ 5. ,

In [ ]:
for i in range(np.shape(unique_filter_iris_transpose)[0]):
  print(f'value: {unique_filter_iris_transpose[i][0]} quantity: {int(unique_filter_iris_transpose[i][1])}')

value: 0.0 quantity: 20
value: 0.1 quantity: 6
value: 0.2 quantity: 28
value: 0.3 quantity: 7
value: 0.4 quantity: 7
value: 0.5 quantity: 1
value: 0.6 quantity: 1
value: 1.0 quantity: 8
value: 1.1 quantity: 4
value: 1.2 quantity: 7
value: 1.3 quantity: 20
value: 1.4 quantity: 20
value: 1.5 quantity: 22
value: 1.6 quantity: 11
value: 1.7 quantity: 6
value: 1.8 quantity: 12
value: 1.9 quantity: 7
value: 2.0 quantity: 7
value: 2.1 quantity: 6
value: 2.2 quantity: 6
value: 2.3 quantity: 10
value: 2.4 quantity: 6
value: 2.5 quantity: 11
value: 2.6 quantity: 5
value: 2.7 quantity: 7
value: 2.8 quantity: 14
value: 2.9 quantity: 10
value: 3.0 quantity: 26
value: 3.1 quantity: 11
value: 3.2 quantity: 13
value: 3.3 quantity: 8
value: 3.4 quantity: 11
value: 3.5 quantity: 8
value: 3.6 quantity: 4
value: 3.7 quantity: 4
value: 3.8 quantity: 7
value: 3.9 quantity: 5
value: 4.0 quantity: 5
value: 4.1 quantity: 4
value: 4.2 quantity: 5
value: 4.3 quantity: 3
value: 4.4 quantity: 8
value: 4.5 quantity

9. Divide the array vertically into 2 equal parts (do not use absolute numbers, there should be two arrays of 4 columns each)

In [ ]:
iris_splited = np.array_split(new_iris, 2, axis = 1)
iris_splited

[array([[5.1, 3.5],
        [4.9, 3. ],
        [4.7, 3.2],
        [4.6, 0. ],
        [5. , 3.6],
        [5.4, 3.9],
        [4.6, 3.4],
        [5. , 3.4],
        [4.4, 2.9],
        [4.9, 3.1],
        [5.4, 3.7],
        [4.8, 0. ],
        [4.8, 3. ],
        [4.3, 3. ],
        [0. , 0. ],
        [5.7, 4.4],
        [5.4, 3.9],
        [5.1, 3.5],
        [5.7, 3.8],
        [5.1, 3.8],
        [0. , 3.4],
        [5.1, 3.7],
        [4.6, 3.6],
        [5.1, 3.3],
        [4.8, 3.4],
        [5. , 3. ],
        [5. , 3.4],
        [5.2, 3.5],
        [5.2, 3.4],
        [4.7, 3.2],
        [4.8, 3.1],
        [5.4, 3.4],
        [5.2, 4.1],
        [5.5, 4.2],
        [4.9, 3.1],
        [5. , 3.2],
        [5.5, 3.5],
        [4.9, 3.1],
        [4.4, 3. ],
        [5.1, 3.4],
        [5. , 3.5],
        [4.5, 2.3],
        [4.4, 3.2],
        [0. , 3.5],
        [5.1, 3.8],
        [4.8, 3. ],
        [5.1, 3.8],
        [4.6, 3.2],
        [5.3, 3.7],
        [5. , 3.3],


In [ ]:
iris1 = iris_splited[0]
iris2 = iris_splited[1]

10. Sort both arrays by the 1st column: 1st by increasing, 2nd by decreasing

In [ ]:
iris1_sorted = iris1[iris1[:,0].argsort()]
iris1_sorted

array([[0. , 3. ],
       [0. , 0. ],
       [0. , 3. ],
       [0. , 3.5],
       [0. , 3.4],
       [4.3, 3. ],
       [4.4, 3. ],
       [4.4, 3.2],
       [4.4, 2.9],
       [4.5, 2.3],
       [4.6, 3.2],
       [4.6, 3.6],
       [4.6, 3.4],
       [4.6, 0. ],
       [4.7, 3.2],
       [4.7, 3.2],
       [4.8, 3. ],
       [4.8, 3. ],
       [4.8, 3.4],
       [4.8, 0. ],
       [4.8, 3.1],
       [4.9, 3.1],
       [4.9, 2.5],
       [4.9, 3.1],
       [4.9, 2.4],
       [4.9, 3.1],
       [4.9, 3. ],
       [5. , 3. ],
       [5. , 3.4],
       [5. , 2. ],
       [5. , 2.3],
       [5. , 3.4],
       [5. , 3.6],
       [5. , 3.2],
       [5. , 3.3],
       [5. , 3.5],
       [5.1, 3.8],
       [5.1, 2.5],
       [5.1, 3.8],
       [5.1, 3.5],
       [5.1, 3.5],
       [5.1, 3.4],
       [5.1, 3.7],
       [5.1, 3.3],
       [5.1, 3.8],
       [5.2, 2.7],
       [5.2, 4.1],
       [5.2, 3.4],
       [5.2, 3.5],
       [5.3, 3.7],
       [5.4, 3.9],
       [5.4, 3.7],
       [5.4,

In [ ]:
iris2_sorted = iris2[iris2[:,0].argsort()[::-1]]
iris2_sorted

array([[6.9, 2.3],
       [6.7, 2. ],
       [6.7, 2.2],
       [6.6, 2.1],
       [6.4, 2. ],
       [6.3, 1.8],
       [6.1, 1.9],
       [6.1, 0. ],
       [6.1, 2.5],
       [6. , 2.5],
       [5.9, 2.3],
       [5.9, 2.1],
       [5.8, 1.8],
       [5.8, 2.2],
       [5.8, 1.6],
       [5.7, 2.5],
       [5.7, 2.3],
       [5.7, 2.1],
       [5.6, 2.1],
       [5.6, 2.2],
       [5.6, 1.4],
       [5.6, 2.4],
       [5.6, 2.4],
       [5.6, 1.8],
       [5.5, 1.8],
       [5.5, 2.1],
       [5.5, 1.8],
       [5.4, 0. ],
       [5.4, 2.1],
       [5.3, 1.9],
       [5.3, 2.3],
       [5.2, 2.3],
       [5.2, 2. ],
       [5.1, 2.4],
       [5.1, 2. ],
       [5.1, 1.8],
       [5.1, 1.9],
       [5.1, 1.5],
       [5.1, 2.3],
       [5.1, 1.9],
       [5.1, 1.6],
       [5. , 1.7],
       [5. , 1.5],
       [5. , 1.9],
       [4.9, 1.5],
       [4.9, 0. ],
       [4.9, 1.8],
       [4.9, 1.8],
       [4.9, 2. ],
       [4.8, 1.8],
       [4.8, 1.4],
       [4.8, 1.8],
       [4.7,

11. Combine both arrays into one

In [ ]:
iris_sorted = np.vstack((iris1_sorted, iris2_sorted))
iris_sorted

array([[0. , 3. ],
       [0. , 0. ],
       [0. , 3. ],
       [0. , 3.5],
       [0. , 3.4],
       [4.3, 3. ],
       [4.4, 3. ],
       [4.4, 3.2],
       [4.4, 2.9],
       [4.5, 2.3],
       [4.6, 3.2],
       [4.6, 3.6],
       [4.6, 3.4],
       [4.6, 0. ],
       [4.7, 3.2],
       [4.7, 3.2],
       [4.8, 3. ],
       [4.8, 3. ],
       [4.8, 3.4],
       [4.8, 0. ],
       [4.8, 3.1],
       [4.9, 3.1],
       [4.9, 2.5],
       [4.9, 3.1],
       [4.9, 2.4],
       [4.9, 3.1],
       [4.9, 3. ],
       [5. , 3. ],
       [5. , 3.4],
       [5. , 2. ],
       [5. , 2.3],
       [5. , 3.4],
       [5. , 3.6],
       [5. , 3.2],
       [5. , 3.3],
       [5. , 3.5],
       [5.1, 3.8],
       [5.1, 2.5],
       [5.1, 3.8],
       [5.1, 3.5],
       [5.1, 3.5],
       [5.1, 3.4],
       [5.1, 3.7],
       [5.1, 3.3],
       [5.1, 3.8],
       [5.2, 2.7],
       [5.2, 4.1],
       [5.2, 3.4],
       [5.2, 3.5],
       [5.3, 3.7],
       [5.4, 3.9],
       [5.4, 3.7],
       [5.4,

12. Знайти найбільш часто повторюване значення в массиві


In [ ]:
iris_repeats = np.unique(new_iris, return_counts=True)
index = np.argmax(iris_repeats[1])
iris_repeatable = iris_repeats[0][index]
iris_repeatable

0.2

13. Write a function that would multiply all values in a column that are less than the average value in this column by 2, and divide the other values by 4



In [ ]:
def calc(array, i):
  mean = np.mean(array, axis = 0)
  result = np.where(array < mean, array * 2, array / 4).transpose()[i]
  return result


Apply the obtained function to the 3rd column

In [ ]:
calc(new_iris, 2)

array([2.8  , 2.8  , 2.6  , 0.   , 2.8  , 3.4  , 2.8  , 0.   , 2.8  ,
       3.   , 3.   , 3.2  , 2.8  , 2.2  , 2.4  , 3.   , 2.6  , 2.8  ,
       3.4  , 3.   , 3.4  , 3.   , 2.   , 3.4  , 3.8  , 3.2  , 3.2  ,
       3.   , 2.8  , 3.2  , 3.2  , 3.   , 3.   , 2.8  , 3.   , 2.4  ,
       2.6  , 3.   , 2.6  , 3.   , 2.6  , 2.6  , 2.6  , 3.2  , 3.8  ,
       2.8  , 3.2  , 2.8  , 3.   , 2.8  , 1.175, 1.125, 1.225, 1.   ,
       1.15 , 1.125, 1.175, 6.6  , 1.15 , 0.975, 7.   , 1.05 , 1.   ,
       1.175, 7.2  , 1.1  , 1.125, 1.025, 1.125, 0.975, 1.2  , 1.   ,
       1.225, 1.175, 1.075, 1.1  , 1.2  , 1.25 , 1.125, 7.   , 0.95 ,
       0.925, 0.975, 1.275, 1.125, 1.125, 1.175, 1.1  , 1.025, 1.   ,
       1.1  , 1.15 , 1.   , 6.6  , 1.05 , 1.05 , 1.05 , 1.075, 0.   ,
       1.025, 1.5  , 1.275, 1.475, 1.4  , 1.45 , 1.65 , 1.125, 1.575,
       1.45 , 1.525, 1.275, 1.325, 1.375, 0.   , 1.275, 1.325, 1.375,
       1.675, 1.725, 1.25 , 1.425, 1.225, 1.675, 1.225, 1.425, 0.   ,
       0.   , 1.225,